3 handlers, step skipping, fedex removed
GraphQL-Portal/graphql-portal-dashboard pull request #331
Opened 2021-03-09 14:17 UTC by msadovyi

2021-03-09 14:36 UTC, germankrause approved these changes

2021-03-09 16:18 UTC, Feshchenko requested changes

2021-03-09 16:32 UTC, msadovyi commented on packages/frontend/src/view/DataSources/AddDataSource/AddDataSource.tsx
> +              {stepsComponents}
step={1}
step={1}

Так же не будет работать?

2021-03-10 13:52 UTC, msadovyi commented on packages/frontend/src/view/DataSources/helpers.ts
> +  if (Object.keys(source?.connector?.properties || {}).length > 0) {
It's overhead because I don't use composed func anywhere. I just have to call Object.keys

2021-03-10 17:40 UTC, Feshchenko commented on packages/frontend/src/presenter/DataSources/useCrunchbaseHandler.ts
> +}: HandlerStep) => {
Remove `HandlerStep`, you provide types for props with `UseCrunchbaseHandlerHook` type

2021-03-10 17:40 UTC, Feshchenko commented on packages/frontend/src/presenter/DataSources/useStripeHandler.ts
> +}: HandlerStep) => {
Remove `HandlerStep` :)

2021-03-10 17:40 UTC, Feshchenko commented on packages/frontend/src/presenter/DataSources/useTwitterHandler.ts
> +}: HandlerStep) => {
Remove `HandlerStep`

2021-03-10 17:54 UTC, merged