Feature/onboarding
GraphQL-Portal/graphql-portal-dashboard pull request #559
Opened 2021-04-12 10:38 UTC by msadovyi

2021-04-12 11:44 UTC, germankrause approved these changes

2021-04-15 14:15 UTC, Feshchenko requested changes

2021-04-15 14:15 UTC, Feshchenko commented on packages/frontend/src/view/Tour/Tour.tsx
> +  const steps: Array<ReactourStep & { buttonDisabled?: boolean }> = [
We should move all this stuff to `contstants`.

2021-04-15 14:15 UTC, Feshchenko commented on packages/frontend/src/view/Tour/Tour.tsx
> +  const emptyElement = <div></div>;
Create components `TourNextButton` and `TourEmptyElement`.

2021-04-15 17:03 UTC, Feshchenko approved these changes

2021-04-15 18:00 UTC, merged